services:
  postgres:
    image: postgres:14.2-alpine
    container_name: forecast-postgres-14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_DB: forecast_app_db
      POSTGRES_USER: admin
      PGUSER: admin
      POSTGRES_PASSWORD: weather0512guru!
    env_file: .env.development.local
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    container_name: forecast-redis
    volumes:
      - redis_data:/var/lib/redis/data
    ports:
     - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
  web:
    build: .
    command: "bundle exec rails s -p 3001 -b '0.0.0.0'"
    environment:
      DB_HOST: postgres
      DB_NAME: forecast_app_db
      DB_USERNAME: admin
      DB_PASSWORD: weather0512guru!
      REDIS_URL: redis
      RAILS_MASTER_KEY:
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
volumes:
  postgres_data: {}
  redis_data: {}
networks:
  default:
    name: forecast_app_default